fieldLayouts:
  6a5e84f2-0a54-49bb-ac1c-dc8d1f5a34ed:
    tabs:
      - elements:
          - autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ""
            label: "Episode Name"
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          - fieldUid: c371a8b8-1c15-4380-b87c-00399aff0f39 # Episode Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          - fieldUid: 48e68ccd-5483-48d2-a2ef-21773e766037 # Episode Number
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          - fieldUid: fa5c5ce5-05e3-4c77-98a7-cf453f6069d0 # Episode Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          - fieldUid: 571f3e60-9b8a-41fc-b0e3-4d589b4c48b6 # Character Relation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: default
hasTitleField: true
name: Default
section: 043e5df9-c995-4f2c-81e4-02d260c771a2 # Netflix
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
