defaultPlacement: end
enableVersioning: true
handle: netflix
name: Netflix
propagationMethod: all
siteSettings:
  551418a0-4fca-4722-8239-21583583a0bb: # Ron Swansum
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
